# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/clement/workspace/Elvex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/clement/workspace/Elvex

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/clement/workspace/Elvex/CMakeFiles /Users/clement/workspace/Elvex//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/clement/workspace/Elvex/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named elvex

# Build rule for target.
elvex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elvex
.PHONY : elvex

# fast build rule for target.
elvex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/build
.PHONY : elvex/fast

#=============================================================================
# Target rules for targets named elvexdebug

# Build rule for target.
elvexdebug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elvexdebug
.PHONY : elvexdebug

# fast build rule for target.
elvexdebug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/build
.PHONY : elvexdebug/fast

#=============================================================================
# Target rules for targets named elvexbuildlexicon

# Build rule for target.
elvexbuildlexicon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elvexbuildlexicon
.PHONY : elvexbuildlexicon

# fast build rule for target.
elvexbuildlexicon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/build
.PHONY : elvexbuildlexicon/fast

#=============================================================================
# Target rules for targets named elvexpostedition_en

# Build rule for target.
elvexpostedition_en: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elvexpostedition_en
.PHONY : elvexpostedition_en

# fast build rule for target.
elvexpostedition_en/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexpostedition_en.dir/build.make CMakeFiles/elvexpostedition_en.dir/build
.PHONY : elvexpostedition_en/fast

#=============================================================================
# Target rules for targets named elvexpostedition_fr

# Build rule for target.
elvexpostedition_fr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elvexpostedition_fr
.PHONY : elvexpostedition_fr

# fast build rule for target.
elvexpostedition_fr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexpostedition_fr.dir/build.make CMakeFiles/elvexpostedition_fr.dir/build
.PHONY : elvexpostedition_fr/fast

src/bitset.o: src/bitset.cc.o
.PHONY : src/bitset.o

# target to build an object file
src/bitset.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/bitset.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/bitset.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/bitset.cc.o
.PHONY : src/bitset.cc.o

src/bitset.i: src/bitset.cc.i
.PHONY : src/bitset.i

# target to preprocess a source file
src/bitset.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/bitset.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/bitset.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/bitset.cc.i
.PHONY : src/bitset.cc.i

src/bitset.s: src/bitset.cc.s
.PHONY : src/bitset.s

# target to generate assembly for a file
src/bitset.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/bitset.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/bitset.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/bitset.cc.s
.PHONY : src/bitset.cc.s

src/buildlexicon.o: src/buildlexicon.cc.o
.PHONY : src/buildlexicon.o

# target to build an object file
src/buildlexicon.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/buildlexicon.cc.o
.PHONY : src/buildlexicon.cc.o

src/buildlexicon.i: src/buildlexicon.cc.i
.PHONY : src/buildlexicon.i

# target to preprocess a source file
src/buildlexicon.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/buildlexicon.cc.i
.PHONY : src/buildlexicon.cc.i

src/buildlexicon.s: src/buildlexicon.cc.s
.PHONY : src/buildlexicon.s

# target to generate assembly for a file
src/buildlexicon.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/buildlexicon.cc.s
.PHONY : src/buildlexicon.cc.s

src/compacted-lexicon-buffer.o: src/compacted-lexicon-buffer.cc.o
.PHONY : src/compacted-lexicon-buffer.o

# target to build an object file
src/compacted-lexicon-buffer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-buffer.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-buffer.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-buffer.cc.o
.PHONY : src/compacted-lexicon-buffer.cc.o

src/compacted-lexicon-buffer.i: src/compacted-lexicon-buffer.cc.i
.PHONY : src/compacted-lexicon-buffer.i

# target to preprocess a source file
src/compacted-lexicon-buffer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-buffer.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-buffer.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-buffer.cc.i
.PHONY : src/compacted-lexicon-buffer.cc.i

src/compacted-lexicon-buffer.s: src/compacted-lexicon-buffer.cc.s
.PHONY : src/compacted-lexicon-buffer.s

# target to generate assembly for a file
src/compacted-lexicon-buffer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-buffer.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-buffer.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-buffer.cc.s
.PHONY : src/compacted-lexicon-buffer.cc.s

src/compacted-lexicon-fsa.o: src/compacted-lexicon-fsa.cc.o
.PHONY : src/compacted-lexicon-fsa.o

# target to build an object file
src/compacted-lexicon-fsa.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-fsa.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-fsa.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-fsa.cc.o
.PHONY : src/compacted-lexicon-fsa.cc.o

src/compacted-lexicon-fsa.i: src/compacted-lexicon-fsa.cc.i
.PHONY : src/compacted-lexicon-fsa.i

# target to preprocess a source file
src/compacted-lexicon-fsa.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-fsa.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-fsa.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-fsa.cc.i
.PHONY : src/compacted-lexicon-fsa.cc.i

src/compacted-lexicon-fsa.s: src/compacted-lexicon-fsa.cc.s
.PHONY : src/compacted-lexicon-fsa.s

# target to generate assembly for a file
src/compacted-lexicon-fsa.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-fsa.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-fsa.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-fsa.cc.s
.PHONY : src/compacted-lexicon-fsa.cc.s

src/compacted-lexicon-info.o: src/compacted-lexicon-info.cc.o
.PHONY : src/compacted-lexicon-info.o

# target to build an object file
src/compacted-lexicon-info.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-info.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-info.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-info.cc.o
.PHONY : src/compacted-lexicon-info.cc.o

src/compacted-lexicon-info.i: src/compacted-lexicon-info.cc.i
.PHONY : src/compacted-lexicon-info.i

# target to preprocess a source file
src/compacted-lexicon-info.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-info.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-info.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-info.cc.i
.PHONY : src/compacted-lexicon-info.cc.i

src/compacted-lexicon-info.s: src/compacted-lexicon-info.cc.s
.PHONY : src/compacted-lexicon-info.s

# target to generate assembly for a file
src/compacted-lexicon-info.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-info.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-info.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-info.cc.s
.PHONY : src/compacted-lexicon-info.cc.s

src/compacted-lexicon-tree.o: src/compacted-lexicon-tree.cc.o
.PHONY : src/compacted-lexicon-tree.o

# target to build an object file
src/compacted-lexicon-tree.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-tree.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-tree.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-tree.cc.o
.PHONY : src/compacted-lexicon-tree.cc.o

src/compacted-lexicon-tree.i: src/compacted-lexicon-tree.cc.i
.PHONY : src/compacted-lexicon-tree.i

# target to preprocess a source file
src/compacted-lexicon-tree.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-tree.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-tree.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-tree.cc.i
.PHONY : src/compacted-lexicon-tree.cc.i

src/compacted-lexicon-tree.s: src/compacted-lexicon-tree.cc.s
.PHONY : src/compacted-lexicon-tree.s

# target to generate assembly for a file
src/compacted-lexicon-tree.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon-tree.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon-tree.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon-tree.cc.s
.PHONY : src/compacted-lexicon-tree.cc.s

src/compacted-lexicon.o: src/compacted-lexicon.cc.o
.PHONY : src/compacted-lexicon.o

# target to build an object file
src/compacted-lexicon.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon.cc.o
.PHONY : src/compacted-lexicon.cc.o

src/compacted-lexicon.i: src/compacted-lexicon.cc.i
.PHONY : src/compacted-lexicon.i

# target to preprocess a source file
src/compacted-lexicon.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon.cc.i
.PHONY : src/compacted-lexicon.cc.i

src/compacted-lexicon.s: src/compacted-lexicon.cc.s
.PHONY : src/compacted-lexicon.s

# target to generate assembly for a file
src/compacted-lexicon.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/compacted-lexicon.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/compacted-lexicon.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/compacted-lexicon.cc.s
.PHONY : src/compacted-lexicon.cc.s

src/elvex.o: src/elvex.cc.o
.PHONY : src/elvex.o

# target to build an object file
src/elvex.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/elvex.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/elvex.cc.o
.PHONY : src/elvex.cc.o

src/elvex.i: src/elvex.cc.i
.PHONY : src/elvex.i

# target to preprocess a source file
src/elvex.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/elvex.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/elvex.cc.i
.PHONY : src/elvex.cc.i

src/elvex.s: src/elvex.cc.s
.PHONY : src/elvex.s

# target to generate assembly for a file
src/elvex.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/elvex.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/elvex.cc.s
.PHONY : src/elvex.cc.s

src/entries.o: src/entries.cc.o
.PHONY : src/entries.o

# target to build an object file
src/entries.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/entries.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/entries.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/entries.cc.o
.PHONY : src/entries.cc.o

src/entries.i: src/entries.cc.i
.PHONY : src/entries.i

# target to preprocess a source file
src/entries.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/entries.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/entries.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/entries.cc.i
.PHONY : src/entries.cc.i

src/entries.s: src/entries.cc.s
.PHONY : src/entries.s

# target to generate assembly for a file
src/entries.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/entries.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/entries.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/entries.cc.s
.PHONY : src/entries.cc.s

src/entry.o: src/entry.cc.o
.PHONY : src/entry.o

# target to build an object file
src/entry.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/entry.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/entry.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/entry.cc.o
.PHONY : src/entry.cc.o

src/entry.i: src/entry.cc.i
.PHONY : src/entry.i

# target to preprocess a source file
src/entry.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/entry.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/entry.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/entry.cc.i
.PHONY : src/entry.cc.i

src/entry.s: src/entry.cc.s
.PHONY : src/entry.s

# target to generate assembly for a file
src/entry.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/entry.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/entry.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/entry.cc.s
.PHONY : src/entry.cc.s

src/environment.o: src/environment.cc.o
.PHONY : src/environment.o

# target to build an object file
src/environment.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/environment.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/environment.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/environment.cc.o
.PHONY : src/environment.cc.o

src/environment.i: src/environment.cc.i
.PHONY : src/environment.i

# target to preprocess a source file
src/environment.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/environment.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/environment.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/environment.cc.i
.PHONY : src/environment.cc.i

src/environment.s: src/environment.cc.s
.PHONY : src/environment.s

# target to generate assembly for a file
src/environment.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/environment.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/environment.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/environment.cc.s
.PHONY : src/environment.cc.s

src/facade.o: src/facade.cc.o
.PHONY : src/facade.o

# target to build an object file
src/facade.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/facade.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/facade.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/facade.cc.o
.PHONY : src/facade.cc.o

src/facade.i: src/facade.cc.i
.PHONY : src/facade.i

# target to preprocess a source file
src/facade.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/facade.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/facade.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/facade.cc.i
.PHONY : src/facade.cc.i

src/facade.s: src/facade.cc.s
.PHONY : src/facade.s

# target to generate assembly for a file
src/facade.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/facade.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/facade.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/facade.cc.s
.PHONY : src/facade.cc.s

src/fatal_exception.o: src/fatal_exception.cc.o
.PHONY : src/fatal_exception.o

# target to build an object file
src/fatal_exception.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/fatal_exception.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/fatal_exception.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/fatal_exception.cc.o
.PHONY : src/fatal_exception.cc.o

src/fatal_exception.i: src/fatal_exception.cc.i
.PHONY : src/fatal_exception.i

# target to preprocess a source file
src/fatal_exception.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/fatal_exception.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/fatal_exception.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/fatal_exception.cc.i
.PHONY : src/fatal_exception.cc.i

src/fatal_exception.s: src/fatal_exception.cc.s
.PHONY : src/fatal_exception.s

# target to generate assembly for a file
src/fatal_exception.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/fatal_exception.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/fatal_exception.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/fatal_exception.cc.s
.PHONY : src/fatal_exception.cc.s

src/feature.o: src/feature.cc.o
.PHONY : src/feature.o

# target to build an object file
src/feature.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/feature.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/feature.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/feature.cc.o
.PHONY : src/feature.cc.o

src/feature.i: src/feature.cc.i
.PHONY : src/feature.i

# target to preprocess a source file
src/feature.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/feature.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/feature.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/feature.cc.i
.PHONY : src/feature.cc.i

src/feature.s: src/feature.cc.s
.PHONY : src/feature.s

# target to generate assembly for a file
src/feature.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/feature.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/feature.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/feature.cc.s
.PHONY : src/feature.cc.s

src/features.o: src/features.cc.o
.PHONY : src/features.o

# target to build an object file
src/features.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/features.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/features.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/features.cc.o
.PHONY : src/features.cc.o

src/features.i: src/features.cc.i
.PHONY : src/features.i

# target to preprocess a source file
src/features.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/features.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/features.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/features.cc.i
.PHONY : src/features.cc.i

src/features.s: src/features.cc.s
.PHONY : src/features.s

# target to generate assembly for a file
src/features.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/features.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/features.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/features.cc.s
.PHONY : src/features.cc.s

src/flags.o: src/flags.cc.o
.PHONY : src/flags.o

# target to build an object file
src/flags.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/flags.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/flags.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/flags.cc.o
.PHONY : src/flags.cc.o

src/flags.i: src/flags.cc.i
.PHONY : src/flags.i

# target to preprocess a source file
src/flags.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/flags.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/flags.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/flags.cc.i
.PHONY : src/flags.cc.i

src/flags.s: src/flags.cc.s
.PHONY : src/flags.s

# target to generate assembly for a file
src/flags.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/flags.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/flags.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/flags.cc.s
.PHONY : src/flags.cc.s

src/forest.o: src/forest.cc.o
.PHONY : src/forest.o

# target to build an object file
src/forest.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/forest.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/forest.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/forest.cc.o
.PHONY : src/forest.cc.o

src/forest.i: src/forest.cc.i
.PHONY : src/forest.i

# target to preprocess a source file
src/forest.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/forest.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/forest.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/forest.cc.i
.PHONY : src/forest.cc.i

src/forest.s: src/forest.cc.s
.PHONY : src/forest.s

# target to generate assembly for a file
src/forest.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/forest.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/forest.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/forest.cc.s
.PHONY : src/forest.cc.s

src/forestidentifier.o: src/forestidentifier.cc.o
.PHONY : src/forestidentifier.o

# target to build an object file
src/forestidentifier.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/forestidentifier.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/forestidentifier.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/forestidentifier.cc.o
.PHONY : src/forestidentifier.cc.o

src/forestidentifier.i: src/forestidentifier.cc.i
.PHONY : src/forestidentifier.i

# target to preprocess a source file
src/forestidentifier.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/forestidentifier.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/forestidentifier.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/forestidentifier.cc.i
.PHONY : src/forestidentifier.cc.i

src/forestidentifier.s: src/forestidentifier.cc.s
.PHONY : src/forestidentifier.s

# target to generate assembly for a file
src/forestidentifier.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/forestidentifier.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/forestidentifier.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/forestidentifier.cc.s
.PHONY : src/forestidentifier.cc.s

src/forestmap.o: src/forestmap.cc.o
.PHONY : src/forestmap.o

# target to build an object file
src/forestmap.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/forestmap.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/forestmap.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/forestmap.cc.o
.PHONY : src/forestmap.cc.o

src/forestmap.i: src/forestmap.cc.i
.PHONY : src/forestmap.i

# target to preprocess a source file
src/forestmap.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/forestmap.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/forestmap.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/forestmap.cc.i
.PHONY : src/forestmap.cc.i

src/forestmap.s: src/forestmap.cc.s
.PHONY : src/forestmap.s

# target to generate assembly for a file
src/forestmap.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/forestmap.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/forestmap.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/forestmap.cc.s
.PHONY : src/forestmap.cc.s

src/item.o: src/item.cc.o
.PHONY : src/item.o

# target to build an object file
src/item.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/item.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/item.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/item.cc.o
.PHONY : src/item.cc.o

src/item.i: src/item.cc.i
.PHONY : src/item.i

# target to preprocess a source file
src/item.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/item.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/item.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/item.cc.i
.PHONY : src/item.cc.i

src/item.s: src/item.cc.s
.PHONY : src/item.s

# target to generate assembly for a file
src/item.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/item.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/item.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/item.cc.s
.PHONY : src/item.cc.s

src/itemset.o: src/itemset.cc.o
.PHONY : src/itemset.o

# target to build an object file
src/itemset.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/itemset.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/itemset.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/itemset.cc.o
.PHONY : src/itemset.cc.o

src/itemset.i: src/itemset.cc.i
.PHONY : src/itemset.i

# target to preprocess a source file
src/itemset.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/itemset.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/itemset.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/itemset.cc.i
.PHONY : src/itemset.cc.i

src/itemset.s: src/itemset.cc.s
.PHONY : src/itemset.s

# target to generate assembly for a file
src/itemset.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/itemset.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/itemset.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/itemset.cc.s
.PHONY : src/itemset.cc.s

src/lexicon.o: src/lexicon.cc.o
.PHONY : src/lexicon.o

# target to build an object file
src/lexicon.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/lexicon.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/lexicon.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/lexicon.cc.o
.PHONY : src/lexicon.cc.o

src/lexicon.i: src/lexicon.cc.i
.PHONY : src/lexicon.i

# target to preprocess a source file
src/lexicon.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/lexicon.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/lexicon.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/lexicon.cc.i
.PHONY : src/lexicon.cc.i

src/lexicon.s: src/lexicon.cc.s
.PHONY : src/lexicon.s

# target to generate assembly for a file
src/lexicon.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/lexicon.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/lexicon.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/lexicon.cc.s
.PHONY : src/lexicon.cc.s

src/listfeatures.o: src/listfeatures.cc.o
.PHONY : src/listfeatures.o

# target to build an object file
src/listfeatures.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/listfeatures.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/listfeatures.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/listfeatures.cc.o
.PHONY : src/listfeatures.cc.o

src/listfeatures.i: src/listfeatures.cc.i
.PHONY : src/listfeatures.i

# target to preprocess a source file
src/listfeatures.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/listfeatures.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/listfeatures.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/listfeatures.cc.i
.PHONY : src/listfeatures.cc.i

src/listfeatures.s: src/listfeatures.cc.s
.PHONY : src/listfeatures.s

# target to generate assembly for a file
src/listfeatures.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/listfeatures.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/listfeatures.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/listfeatures.cc.s
.PHONY : src/listfeatures.cc.s

src/memoization-map.o: src/memoization-map.cc.o
.PHONY : src/memoization-map.o

# target to build an object file
src/memoization-map.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/memoization-map.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/memoization-map.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/memoization-map.cc.o
.PHONY : src/memoization-map.cc.o

src/memoization-map.i: src/memoization-map.cc.i
.PHONY : src/memoization-map.i

# target to preprocess a source file
src/memoization-map.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/memoization-map.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/memoization-map.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/memoization-map.cc.i
.PHONY : src/memoization-map.cc.i

src/memoization-map.s: src/memoization-map.cc.s
.PHONY : src/memoization-map.s

# target to generate assembly for a file
src/memoization-map.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/memoization-map.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/memoization-map.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/memoization-map.cc.s
.PHONY : src/memoization-map.cc.s

src/memoization-value.o: src/memoization-value.cc.o
.PHONY : src/memoization-value.o

# target to build an object file
src/memoization-value.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/memoization-value.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/memoization-value.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/memoization-value.cc.o
.PHONY : src/memoization-value.cc.o

src/memoization-value.i: src/memoization-value.cc.i
.PHONY : src/memoization-value.i

# target to preprocess a source file
src/memoization-value.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/memoization-value.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/memoization-value.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/memoization-value.cc.i
.PHONY : src/memoization-value.cc.i

src/memoization-value.s: src/memoization-value.cc.s
.PHONY : src/memoization-value.s

# target to generate assembly for a file
src/memoization-value.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/memoization-value.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/memoization-value.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/memoization-value.cc.s
.PHONY : src/memoization-value.cc.s

src/node.o: src/node.cc.o
.PHONY : src/node.o

# target to build an object file
src/node.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/node.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/node.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/node.cc.o
.PHONY : src/node.cc.o

src/node.i: src/node.cc.i
.PHONY : src/node.i

# target to preprocess a source file
src/node.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/node.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/node.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/node.cc.i
.PHONY : src/node.cc.i

src/node.s: src/node.cc.s
.PHONY : src/node.s

# target to generate assembly for a file
src/node.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/node.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/node.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/node.cc.s
.PHONY : src/node.cc.s

src/pairp.o: src/pairp.cc.o
.PHONY : src/pairp.o

# target to build an object file
src/pairp.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/pairp.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/pairp.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/pairp.cc.o
.PHONY : src/pairp.cc.o

src/pairp.i: src/pairp.cc.i
.PHONY : src/pairp.i

# target to preprocess a source file
src/pairp.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/pairp.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/pairp.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/pairp.cc.i
.PHONY : src/pairp.cc.i

src/pairp.s: src/pairp.cc.s
.PHONY : src/pairp.s

# target to generate assembly for a file
src/pairp.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/pairp.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/pairp.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/pairp.cc.s
.PHONY : src/pairp.cc.s

src/parser.o: src/parser.cc.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/parser.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/parser.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/parser.cc.o
.PHONY : src/parser.cc.o

src/parser.i: src/parser.cc.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/parser.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/parser.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/parser.cc.i
.PHONY : src/parser.cc.i

src/parser.s: src/parser.cc.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/parser.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/parser.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/parser.cc.s
.PHONY : src/parser.cc.s

src/parser_exception.o: src/parser_exception.cc.o
.PHONY : src/parser_exception.o

# target to build an object file
src/parser_exception.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/parser_exception.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/parser_exception.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/parser_exception.cc.o
.PHONY : src/parser_exception.cc.o

src/parser_exception.i: src/parser_exception.cc.i
.PHONY : src/parser_exception.i

# target to preprocess a source file
src/parser_exception.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/parser_exception.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/parser_exception.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/parser_exception.cc.i
.PHONY : src/parser_exception.cc.i

src/parser_exception.s: src/parser_exception.cc.s
.PHONY : src/parser_exception.s

# target to generate assembly for a file
src/parser_exception.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/parser_exception.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/parser_exception.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/parser_exception.cc.s
.PHONY : src/parser_exception.cc.s

src/postedition_en.o: src/postedition_en.cc.o
.PHONY : src/postedition_en.o

# target to build an object file
src/postedition_en.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexpostedition_en.dir/build.make CMakeFiles/elvexpostedition_en.dir/src/postedition_en.cc.o
.PHONY : src/postedition_en.cc.o

src/postedition_en.i: src/postedition_en.cc.i
.PHONY : src/postedition_en.i

# target to preprocess a source file
src/postedition_en.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexpostedition_en.dir/build.make CMakeFiles/elvexpostedition_en.dir/src/postedition_en.cc.i
.PHONY : src/postedition_en.cc.i

src/postedition_en.s: src/postedition_en.cc.s
.PHONY : src/postedition_en.s

# target to generate assembly for a file
src/postedition_en.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexpostedition_en.dir/build.make CMakeFiles/elvexpostedition_en.dir/src/postedition_en.cc.s
.PHONY : src/postedition_en.cc.s

src/postedition_fr.o: src/postedition_fr.cc.o
.PHONY : src/postedition_fr.o

# target to build an object file
src/postedition_fr.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexpostedition_fr.dir/build.make CMakeFiles/elvexpostedition_fr.dir/src/postedition_fr.cc.o
.PHONY : src/postedition_fr.cc.o

src/postedition_fr.i: src/postedition_fr.cc.i
.PHONY : src/postedition_fr.i

# target to preprocess a source file
src/postedition_fr.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexpostedition_fr.dir/build.make CMakeFiles/elvexpostedition_fr.dir/src/postedition_fr.cc.i
.PHONY : src/postedition_fr.cc.i

src/postedition_fr.s: src/postedition_fr.cc.s
.PHONY : src/postedition_fr.s

# target to generate assembly for a file
src/postedition_fr.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexpostedition_fr.dir/build.make CMakeFiles/elvexpostedition_fr.dir/src/postedition_fr.cc.s
.PHONY : src/postedition_fr.cc.s

src/rule.o: src/rule.cc.o
.PHONY : src/rule.o

# target to build an object file
src/rule.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/rule.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/rule.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/rule.cc.o
.PHONY : src/rule.cc.o

src/rule.i: src/rule.cc.i
.PHONY : src/rule.i

# target to preprocess a source file
src/rule.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/rule.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/rule.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/rule.cc.i
.PHONY : src/rule.cc.i

src/rule.s: src/rule.cc.s
.PHONY : src/rule.s

# target to generate assembly for a file
src/rule.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/rule.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/rule.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/rule.cc.s
.PHONY : src/rule.cc.s

src/rules.o: src/rules.cc.o
.PHONY : src/rules.o

# target to build an object file
src/rules.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/rules.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/rules.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/rules.cc.o
.PHONY : src/rules.cc.o

src/rules.i: src/rules.cc.i
.PHONY : src/rules.i

# target to preprocess a source file
src/rules.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/rules.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/rules.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/rules.cc.i
.PHONY : src/rules.cc.i

src/rules.s: src/rules.cc.s
.PHONY : src/rules.s

# target to generate assembly for a file
src/rules.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/rules.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/rules.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/rules.cc.s
.PHONY : src/rules.cc.s

src/ruleslex.o: src/ruleslex.cc.o
.PHONY : src/ruleslex.o

# target to build an object file
src/ruleslex.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/ruleslex.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/ruleslex.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/ruleslex.cc.o
.PHONY : src/ruleslex.cc.o

src/ruleslex.i: src/ruleslex.cc.i
.PHONY : src/ruleslex.i

# target to preprocess a source file
src/ruleslex.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/ruleslex.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/ruleslex.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/ruleslex.cc.i
.PHONY : src/ruleslex.cc.i

src/ruleslex.s: src/ruleslex.cc.s
.PHONY : src/ruleslex.s

# target to generate assembly for a file
src/ruleslex.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/ruleslex.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/ruleslex.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/ruleslex.cc.s
.PHONY : src/ruleslex.cc.s

src/rulesyacc.o: src/rulesyacc.cc.o
.PHONY : src/rulesyacc.o

# target to build an object file
src/rulesyacc.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/rulesyacc.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/rulesyacc.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/rulesyacc.cc.o
.PHONY : src/rulesyacc.cc.o

src/rulesyacc.i: src/rulesyacc.cc.i
.PHONY : src/rulesyacc.i

# target to preprocess a source file
src/rulesyacc.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/rulesyacc.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/rulesyacc.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/rulesyacc.cc.i
.PHONY : src/rulesyacc.cc.i

src/rulesyacc.s: src/rulesyacc.cc.s
.PHONY : src/rulesyacc.s

# target to generate assembly for a file
src/rulesyacc.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/rulesyacc.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/rulesyacc.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/rulesyacc.cc.s
.PHONY : src/rulesyacc.cc.s

src/serializable.o: src/serializable.cc.o
.PHONY : src/serializable.o

# target to build an object file
src/serializable.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/serializable.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/serializable.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/serializable.cc.o
.PHONY : src/serializable.cc.o

src/serializable.i: src/serializable.cc.i
.PHONY : src/serializable.i

# target to preprocess a source file
src/serializable.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/serializable.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/serializable.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/serializable.cc.i
.PHONY : src/serializable.cc.i

src/serializable.s: src/serializable.cc.s
.PHONY : src/serializable.s

# target to generate assembly for a file
src/serializable.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/serializable.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/serializable.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/serializable.cc.s
.PHONY : src/serializable.cc.s

src/statement.o: src/statement.cc.o
.PHONY : src/statement.o

# target to build an object file
src/statement.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/statement.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/statement.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/statement.cc.o
.PHONY : src/statement.cc.o

src/statement.i: src/statement.cc.i
.PHONY : src/statement.i

# target to preprocess a source file
src/statement.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/statement.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/statement.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/statement.cc.i
.PHONY : src/statement.cc.i

src/statement.s: src/statement.cc.s
.PHONY : src/statement.s

# target to generate assembly for a file
src/statement.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/statement.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/statement.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/statement.cc.s
.PHONY : src/statement.cc.s

src/statements.o: src/statements.cc.o
.PHONY : src/statements.o

# target to build an object file
src/statements.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/statements.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/statements.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/statements.cc.o
.PHONY : src/statements.cc.o

src/statements.i: src/statements.cc.i
.PHONY : src/statements.i

# target to preprocess a source file
src/statements.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/statements.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/statements.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/statements.cc.i
.PHONY : src/statements.cc.i

src/statements.s: src/statements.cc.s
.PHONY : src/statements.s

# target to generate assembly for a file
src/statements.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/statements.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/statements.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/statements.cc.s
.PHONY : src/statements.cc.s

src/synthesizer.o: src/synthesizer.cc.o
.PHONY : src/synthesizer.o

# target to build an object file
src/synthesizer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/synthesizer.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/synthesizer.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/synthesizer.cc.o
.PHONY : src/synthesizer.cc.o

src/synthesizer.i: src/synthesizer.cc.i
.PHONY : src/synthesizer.i

# target to preprocess a source file
src/synthesizer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/synthesizer.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/synthesizer.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/synthesizer.cc.i
.PHONY : src/synthesizer.cc.i

src/synthesizer.s: src/synthesizer.cc.s
.PHONY : src/synthesizer.s

# target to generate assembly for a file
src/synthesizer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/synthesizer.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/synthesizer.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/synthesizer.cc.s
.PHONY : src/synthesizer.cc.s

src/terms.o: src/terms.cc.o
.PHONY : src/terms.o

# target to build an object file
src/terms.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/terms.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/terms.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/terms.cc.o
.PHONY : src/terms.cc.o

src/terms.i: src/terms.cc.i
.PHONY : src/terms.i

# target to preprocess a source file
src/terms.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/terms.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/terms.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/terms.cc.i
.PHONY : src/terms.cc.i

src/terms.s: src/terms.cc.s
.PHONY : src/terms.s

# target to generate assembly for a file
src/terms.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/terms.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/terms.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/terms.cc.s
.PHONY : src/terms.cc.s

src/uniq-id.o: src/uniq-id.cc.o
.PHONY : src/uniq-id.o

# target to build an object file
src/uniq-id.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/uniq-id.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/uniq-id.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/uniq-id.cc.o
.PHONY : src/uniq-id.cc.o

src/uniq-id.i: src/uniq-id.cc.i
.PHONY : src/uniq-id.i

# target to preprocess a source file
src/uniq-id.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/uniq-id.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/uniq-id.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/uniq-id.cc.i
.PHONY : src/uniq-id.cc.i

src/uniq-id.s: src/uniq-id.cc.s
.PHONY : src/uniq-id.s

# target to generate assembly for a file
src/uniq-id.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/uniq-id.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/uniq-id.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/uniq-id.cc.s
.PHONY : src/uniq-id.cc.s

src/usage_exception.o: src/usage_exception.cc.o
.PHONY : src/usage_exception.o

# target to build an object file
src/usage_exception.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/usage_exception.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/usage_exception.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/usage_exception.cc.o
.PHONY : src/usage_exception.cc.o

src/usage_exception.i: src/usage_exception.cc.i
.PHONY : src/usage_exception.i

# target to preprocess a source file
src/usage_exception.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/usage_exception.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/usage_exception.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/usage_exception.cc.i
.PHONY : src/usage_exception.cc.i

src/usage_exception.s: src/usage_exception.cc.s
.PHONY : src/usage_exception.s

# target to generate assembly for a file
src/usage_exception.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/usage_exception.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/usage_exception.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/usage_exception.cc.s
.PHONY : src/usage_exception.cc.s

src/value.o: src/value.cc.o
.PHONY : src/value.o

# target to build an object file
src/value.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/value.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/value.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/value.cc.o
.PHONY : src/value.cc.o

src/value.i: src/value.cc.i
.PHONY : src/value.i

# target to preprocess a source file
src/value.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/value.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/value.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/value.cc.i
.PHONY : src/value.cc.i

src/value.s: src/value.cc.s
.PHONY : src/value.s

# target to generate assembly for a file
src/value.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/value.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/value.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/value.cc.s
.PHONY : src/value.cc.s

src/variableflag.o: src/variableflag.cc.o
.PHONY : src/variableflag.o

# target to build an object file
src/variableflag.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/variableflag.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/variableflag.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/variableflag.cc.o
.PHONY : src/variableflag.cc.o

src/variableflag.i: src/variableflag.cc.i
.PHONY : src/variableflag.i

# target to preprocess a source file
src/variableflag.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/variableflag.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/variableflag.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/variableflag.cc.i
.PHONY : src/variableflag.cc.i

src/variableflag.s: src/variableflag.cc.s
.PHONY : src/variableflag.s

# target to generate assembly for a file
src/variableflag.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/variableflag.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/variableflag.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/variableflag.cc.s
.PHONY : src/variableflag.cc.s

src/vartable.o: src/vartable.cc.o
.PHONY : src/vartable.o

# target to build an object file
src/vartable.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/vartable.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/vartable.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/vartable.cc.o
.PHONY : src/vartable.cc.o

src/vartable.i: src/vartable.cc.i
.PHONY : src/vartable.i

# target to preprocess a source file
src/vartable.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/vartable.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/vartable.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/vartable.cc.i
.PHONY : src/vartable.cc.i

src/vartable.s: src/vartable.cc.s
.PHONY : src/vartable.s

# target to generate assembly for a file
src/vartable.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvex.dir/build.make CMakeFiles/elvex.dir/src/vartable.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexdebug.dir/build.make CMakeFiles/elvexdebug.dir/src/vartable.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elvexbuildlexicon.dir/build.make CMakeFiles/elvexbuildlexicon.dir/src/vartable.cc.s
.PHONY : src/vartable.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... elvex"
	@echo "... elvexbuildlexicon"
	@echo "... elvexdebug"
	@echo "... elvexpostedition_en"
	@echo "... elvexpostedition_fr"
	@echo "... src/bitset.o"
	@echo "... src/bitset.i"
	@echo "... src/bitset.s"
	@echo "... src/buildlexicon.o"
	@echo "... src/buildlexicon.i"
	@echo "... src/buildlexicon.s"
	@echo "... src/compacted-lexicon-buffer.o"
	@echo "... src/compacted-lexicon-buffer.i"
	@echo "... src/compacted-lexicon-buffer.s"
	@echo "... src/compacted-lexicon-fsa.o"
	@echo "... src/compacted-lexicon-fsa.i"
	@echo "... src/compacted-lexicon-fsa.s"
	@echo "... src/compacted-lexicon-info.o"
	@echo "... src/compacted-lexicon-info.i"
	@echo "... src/compacted-lexicon-info.s"
	@echo "... src/compacted-lexicon-tree.o"
	@echo "... src/compacted-lexicon-tree.i"
	@echo "... src/compacted-lexicon-tree.s"
	@echo "... src/compacted-lexicon.o"
	@echo "... src/compacted-lexicon.i"
	@echo "... src/compacted-lexicon.s"
	@echo "... src/elvex.o"
	@echo "... src/elvex.i"
	@echo "... src/elvex.s"
	@echo "... src/entries.o"
	@echo "... src/entries.i"
	@echo "... src/entries.s"
	@echo "... src/entry.o"
	@echo "... src/entry.i"
	@echo "... src/entry.s"
	@echo "... src/environment.o"
	@echo "... src/environment.i"
	@echo "... src/environment.s"
	@echo "... src/facade.o"
	@echo "... src/facade.i"
	@echo "... src/facade.s"
	@echo "... src/fatal_exception.o"
	@echo "... src/fatal_exception.i"
	@echo "... src/fatal_exception.s"
	@echo "... src/feature.o"
	@echo "... src/feature.i"
	@echo "... src/feature.s"
	@echo "... src/features.o"
	@echo "... src/features.i"
	@echo "... src/features.s"
	@echo "... src/flags.o"
	@echo "... src/flags.i"
	@echo "... src/flags.s"
	@echo "... src/forest.o"
	@echo "... src/forest.i"
	@echo "... src/forest.s"
	@echo "... src/forestidentifier.o"
	@echo "... src/forestidentifier.i"
	@echo "... src/forestidentifier.s"
	@echo "... src/forestmap.o"
	@echo "... src/forestmap.i"
	@echo "... src/forestmap.s"
	@echo "... src/item.o"
	@echo "... src/item.i"
	@echo "... src/item.s"
	@echo "... src/itemset.o"
	@echo "... src/itemset.i"
	@echo "... src/itemset.s"
	@echo "... src/lexicon.o"
	@echo "... src/lexicon.i"
	@echo "... src/lexicon.s"
	@echo "... src/listfeatures.o"
	@echo "... src/listfeatures.i"
	@echo "... src/listfeatures.s"
	@echo "... src/memoization-map.o"
	@echo "... src/memoization-map.i"
	@echo "... src/memoization-map.s"
	@echo "... src/memoization-value.o"
	@echo "... src/memoization-value.i"
	@echo "... src/memoization-value.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/pairp.o"
	@echo "... src/pairp.i"
	@echo "... src/pairp.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/parser_exception.o"
	@echo "... src/parser_exception.i"
	@echo "... src/parser_exception.s"
	@echo "... src/postedition_en.o"
	@echo "... src/postedition_en.i"
	@echo "... src/postedition_en.s"
	@echo "... src/postedition_fr.o"
	@echo "... src/postedition_fr.i"
	@echo "... src/postedition_fr.s"
	@echo "... src/rule.o"
	@echo "... src/rule.i"
	@echo "... src/rule.s"
	@echo "... src/rules.o"
	@echo "... src/rules.i"
	@echo "... src/rules.s"
	@echo "... src/ruleslex.o"
	@echo "... src/ruleslex.i"
	@echo "... src/ruleslex.s"
	@echo "... src/rulesyacc.o"
	@echo "... src/rulesyacc.i"
	@echo "... src/rulesyacc.s"
	@echo "... src/serializable.o"
	@echo "... src/serializable.i"
	@echo "... src/serializable.s"
	@echo "... src/statement.o"
	@echo "... src/statement.i"
	@echo "... src/statement.s"
	@echo "... src/statements.o"
	@echo "... src/statements.i"
	@echo "... src/statements.s"
	@echo "... src/synthesizer.o"
	@echo "... src/synthesizer.i"
	@echo "... src/synthesizer.s"
	@echo "... src/terms.o"
	@echo "... src/terms.i"
	@echo "... src/terms.s"
	@echo "... src/uniq-id.o"
	@echo "... src/uniq-id.i"
	@echo "... src/uniq-id.s"
	@echo "... src/usage_exception.o"
	@echo "... src/usage_exception.i"
	@echo "... src/usage_exception.s"
	@echo "... src/value.o"
	@echo "... src/value.i"
	@echo "... src/value.s"
	@echo "... src/variableflag.o"
	@echo "... src/variableflag.i"
	@echo "... src/variableflag.s"
	@echo "... src/vartable.o"
	@echo "... src/vartable.i"
	@echo "... src/vartable.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

