#*************************************************
#
# ELVEX
#
# Copyright 2014-2023 LABRI,
# CNRS (UMR 5800), the University of Bordeaux,
# and the Bordeaux INP
#
# Author:
# Lionel Clément
# LaBRI - Université Bordeaux 
# 351, cours de la Libération
# 33405 Talence Cedex - France
# lionel.clement@u-bordeaux.fr
#
# This file is part of ELVEX.
#
#**************************************************

# Phony targets to avoid conflicts with files of the same name
.PHONY: test all_pdf clean

.SUFFIXES: .input .rules .lexicon .output .xml .dot .pdf .fsa .html .morpho .pattern .stdin

# Name of the Elvex program
elvex = bin/elvex
elvexlexicon = bin/elvexlexicon
# Check the existence of dot (Graphviz)
DOT = $(shell command -v dot 2> /dev/null)
# Check the existence of xsltproc
XSLTPROC = $(shell command -v xsltproc 2> /dev/null)
xslfile = xsl/xml2CS-dot-graph.xsl
python = python3

# Directory where test files are located
test_dir = test

# List of all input files
input_files = $(wildcard $(test_dir)/*.input)
stdin_files = $(wildcard $(test_dir)/*.stdin)

# Specific targets to generate all *.output files
output_files = $(patsubst $(test_dir)/%.input,$(test_dir)/%.output,$(input_files)) 
output_files += $(patsubst $(test_dir)/%.stdin,$(test_dir)/%.output,$(stdin_files)) 

# Target to run tests
test: $(output_files)
	@for file in $(output_files); do \
		base=$$(basename $$file .output); \
		sort $(test_dir)/$$base.output > $(test_dir)/$$base.output.sorted; \
		sort $(test_dir)/$$base.test > $(test_dir)/$$base.test.sorted; \
		if diff $(test_dir)/$$base.output.sorted $(test_dir)/$$base.test.sorted> /dev/null 2>&1; then \
			echo "Test $$base passed."; \
		else \
			echo "Test $$base failed. Please check the trace with --trace options."; \
		fi; \
		rm  $(test_dir)/$$base.output.sorted $(test_dir)/$$base.test.sorted; \
	done

# Specific targets to generate all *.pdf files
all_pdf: $(patsubst $(test_dir)/%.input,$(test_dir)/%.pdf,$(input_files))

# Rule to generate an *.output file from an *.input file
%.output: %.input %.rules %.lexicon $(elvex)
	@echo "build $@ from $^"
	@if test -f $*.pattern; then \
		make -f Makefile.test $*.fsa ; \
		$(if $(wildcard $*.macros), \
			$(elvex) --macros-file $*.macros --compacted-lexicon-file $* --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< > $@, \
			$(elvex) --compacted-lexicon-file $* --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< > $@); \
	else \
		$(if $(wildcard $*.macros),\
		 	$(elvex) --macros-file $*.macros --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< > $@, \
		 	$(elvex) --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< > $@); \
	fi

# Rule to generate an *.output file from an *.input file
%.output: %.rules %.lexicon %.stdin $(elvex)
	@echo "build $@ from $^"
	@if test -f $*.pattern; then \
		make -f Makefile.test $*.fsa ; \
		$(if $(wildcard $*.macros), \
			$(elvex) --macros-file $*.macros --compacted-lexicon-file $* --rules-file $*.rules --lexicon-file $*.lexicon < $*.stdin > $@, \
			$(elvex) --compacted-lexicon-file $* --rules-file $*.rules --lexicon-file $*.lexicon < $*.stdin > $@); \
	else \
		$(if $(wildcard $*.macros),\
		 	$(elvex) --macros-file $*.macros --rules-file $*.rules --lexicon-file $*.lexicon < $*.stdin > $@, \
		 	$(elvex) --rules-file $*.rules --lexicon-file $*.lexicon < $*.stdin > $@); \
	fi

# Rule to generate an *.output file from an *.input file
%.html: %.input %.rules %.lexicon $(elvex)
	@echo "build $@ from $^"
	@if test -f $*.pattern; then \
		make -f Makefile.test $*.fsa ; \
		$(if $(wildcard $*.macros), \
			$(elvex) --trace --macros-file $*.macros --compacted-lexicon-file $* --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< > $@, \
			$(elvex) --trace --compacted-lexicon-file $* --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< > $@); \
	else \
		$(if $(wildcard $*.macros),\
		 	$(elvex) --trace --macros-file $*.macros --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< > $@, \
		 	$(elvex) --trace --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< > $@); \
	fi

%.xml: %.input %.rules %.lexicon $(elvex)
	@echo "build $@ from $^"
	@if test -f $*.pattern; then \
		make -f Makefile.test $*.fsa ; \
		$(if $(wildcard $*.macros), \
			$(elvex) --macros-file $*.macros --compacted-lexicon-file $* --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< -xml $*.xml > /dev/null 2>&1, \
			$(elvex) --compacted-lexicon-file $* --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< -xml $*.xml > /dev/null 2>&1); \
	else \
		$(if $(wildcard $*.macros),\
		 	$(elvex) --macros-file $*.macros --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< -xml $*.xml > /dev/null 2>&1, \
		 	$(elvex) --rules-file $*.rules --lexicon-file $*.lexicon --input-file $< -xml $*.xml > /dev/null 2>&1); \
	fi

# Check the existence of xsltproc
%.dot: %.xml $(xslfile)
	@echo "build $@ from $^"
	@if test -z "$(XSLTPROC)"; then \
		echo "Error: xsltproc is not installed."; \
	else \
		$(XSLTPROC) $(xslfile) $*.xml > $@; \
	fi

# Check the existence of dot (Graphviz)
%.pdf: %.dot
	@echo "build $@ from $^"
	@if test -z "$(DOT)" ; then \
		echo "Error: dot (Graphviz) is not installed."; \
	else \
		$(DOT) -T pdf -o $@ $<; \
	fi

%.fsa: %.morpho %.pattern
	@echo "build $@ from $^"
	$(if $(wildcard $*.macros), \
			$(elvexlexicon) --compacted-lexicon-file $* --macros-file $*.macros -patternFile $*.pattern -morphoFile $*.morpho build, \
			$(elvexlexicon) --compacted-lexicon-file $* -patternFile $*.pattern -morphoFile $*.morpho build ); \
	
%.morpho:
	@echo "build $@"

%.pattern:
	@echo "build $@"

# Cleaning generated files
clean:
	@rm -f $(test_dir)/*.output $(test_dir)/*.pdf $(test_dir)/*.fsa $(test_dir)/*.tbl
