USE elvex;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS display_name VARCHAR(120) NOT NULL DEFAULT '' AFTER email,
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) DEFAULT NULL AFTER display_name,
    ADD COLUMN IF NOT EXISTS signup_code VARCHAR(255) DEFAULT NULL AFTER password_hash,
    ADD COLUMN IF NOT EXISTS signup_code_expires_at DATETIME DEFAULT NULL AFTER signup_code,
    ADD COLUMN IF NOT EXISTS password_reset_token VARCHAR(255) DEFAULT NULL AFTER signup_code_expires_at,
    ADD COLUMN IF NOT EXISTS password_reset_expires_at DATETIME DEFAULT NULL AFTER password_reset_token,
    ADD COLUMN IF NOT EXISTS is_verified TINYINT(1) NOT NULL DEFAULT 0 AFTER password_reset_expires_at,
    ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER is_verified,
    ADD COLUMN IF NOT EXISTS updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
